id: P005591
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4592
  title: དཔྱད་རྩོམ་ནོར་བུའི་ཕྲེང་བ། ༼དེབ་ཕྲེང་བཅུ་པ།༽
  author: ''
  volumes:
    0ca8474c33b54eaf90b390a353537463:
      image_group_id: I1KG20937
      title: ''
      volume_number: 1
      total_pages: 226
