id: P005591
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:05:21.713664
source_metadata:
  id: bdr:W2DB4592
  title: དཔྱད་རྩོམ་ནོར་བུའི་ཕྲེང་བ། ༼དེབ་ཕྲེང་བཅུ་པ།༽
  author: ''
  volumes:
    0ca8474c33b54eaf90b390a353537463:
      image_group_id: I1KG20937
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
